export interface Department {
  id: string;
  name: string;
  cities: string[];
  shipping: {
    servientrega: number;
    interrapidisimo: number;
    days: string;
  };
}

// Envíos calculados desde Villavicencio (Meta)
export const COLOMBIA_DEPARTMENTS: Department[] = [
  { id: 'AMAZONAS', name: 'Amazonas', cities: ['Leticia', 'Puerto Amazonas', 'Puerto Alegría', 'Puerto Arica', 'La Chorrera', 'El Encanto', 'La Pedrera', 'Mirití', 'Tarapacá', 'Área de Regularización'], shipping: { servientrega: 45000, interrapidisimo: 38000, days: '6-7 días' } },
  { id: 'ANTIOQUIA', name: 'Antioquia', cities: ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Sabaneta', 'Apartadó', 'Rionegro', 'Turbo', 'Carepa', 'Chigorodó', 'La Ceja', 'Fredonia', 'Santa Fe de Antioquia', 'Girardota', 'Copacabana', 'Caucasia', 'Zaragoza', 'Segovia', 'Necoclí', 'Urabá', 'Barbosa', 'La Estrella', 'Sabanalarga', 'Amagá', 'Andes', 'Armenia', 'Betania', 'Briceño', 'Buriticá', 'Cáceres', 'Caicedo', 'Camilo C', 'Caracolí', 'Caramanta', 'Chalota', 'Concordia', 'Dabeiba', 'Ebéjico', 'El Bagre', 'Frontino', 'Giraldo', 'Heliconia', 'Intrantu', 'Jardín', 'Jericó', 'La Pintada', 'Liborina', 'Maceo', 'Marinilla', 'Montebello', 'Nariño', 'Olaya', 'Peñol', 'Pueblorrico', 'Puerto Berrío', 'Puerto Nare', 'Puerto Triunfo', 'Remedios', 'Retiro', 'Sahagún', 'San Carlos', 'San Francisco', 'San Jerónimo', 'San Luis', 'San Pedro', 'San Rafael', 'San Roque', 'Santa Bárbara', 'Santodomingo', 'Sonson', 'Sopetrán', 'Támesis', 'Tarazá', 'Titiribí', 'Toledo', 'Turrialba', 'Urrao', 'Valdivia', 'Vegachí', 'Venecia', 'Yalí', 'Yarumal', 'Yolombó', 'Yondó', 'Zamalv'], shipping: { servientrega: 12000, interrapidisimo: 10000, days: '2-3 días' } },
  { id: 'ARAUCA', name: 'Arauca', cities: ['Arauca', 'Saravena', 'Tame', 'Puerto Rondón', 'Arauquita', 'Cravo Norte', 'Fortul', 'Puerto Carreño', 'Casanare', 'La Salada', 'Cubará'], shipping: { servientrega: 18000, interrapidisimo: 15000, days: '3-4 días' } },
  { id: 'ATLANTICO', name: 'Atlántico', cities: ['Barranquilla', 'Soledad', 'Malambo', 'Puerto Colombia', 'Galapa', 'Baranoa', 'Campo de la Cruz', 'Candelaria', 'Juan de Acosta', 'Luruaco', 'Manatí', 'Palmar de Varela', 'Ponedera', 'Remolino', 'Sabanalarga', 'Santa Lucía', 'Santo Tomás', 'Suán', 'Tubará', 'Usiacurí'], shipping: { servientrega: 18000, interrapidisimo: 15000, days: '3-4 días' } },
  { id: 'BOLIVAR', name: 'Bolívar', cities: ['Cartagena', 'Barranco de Loba', 'Clemencia', 'Córdoba', 'El Carmen de Bolívar', 'El Guamo', 'Hatillo de Loba', 'Magangué', 'Mahates', 'Margarita', 'María La Baja', 'Mompox', 'Montecristo', 'Plato', 'Regidor', 'Río Viejo', 'San Cristóbal', 'San Estanislao', 'San Fernando', 'San Jacinto', 'San Juan Nepomuceno', 'Santa Rosa', 'Santa Rosa del Sur', 'Simití', 'Soplaviento', 'Talaigua Nuevo', 'Turbaco', 'Turbaná', 'Villanueva', 'Zambrano'], shipping: { servientrega: 20000, interrapidisimo: 17000, days: '3-4 días' } },
  { id: 'BOYACA', name: 'Boyacá', cities: ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Paipa', 'Moniquirá', 'Samacá', 'Nobsa', 'Villa de Leyva', 'Sotaquirá', 'Tibasosa', 'Ráquira', 'Tota', 'Cómbita', 'Chivatá', 'Oicatá', 'Toca', 'Tuta', 'Arcabuco', 'Belén', 'Berbeo', 'Beteitiva', 'Boavita', 'Boyacá', 'Buenavista', 'Calancho', 'Caminay', 'Chaquiro', 'Chiscas', 'Chita', 'Chitaraque', 'Ciéaga', 'Coper', 'Corrales', 'Covarachía', 'Cubará', 'Cucaita', 'Cuítiva', 'Chinavita', 'Durania', 'El Cocuy', 'El Espino', 'Firavitoba', 'Floresta', 'Gachantivá', 'Gámeza', 'Garagoa', 'Guacamayas', 'Guaduas', 'Guayatá', 'Güicán', 'Iza', 'Jenesano', 'Jericó', 'La Uvita', 'Labranzagrande', 'Macanal', 'Maripí', 'Mongua', 'Monguí', 'Moniquirá', 'Motavita', 'Muzo', 'Neira', 'Otanche', 'Pachavita', 'Páez', 'Paipa', 'Pajarito', 'Panqueba', 'Pauna', 'Paya', 'Paz de Río', 'Pesca', 'Pisba', 'Puerto Boyacá', 'Quípama', 'Ramiriquí', 'Rondón', 'Saboyá', 'Sáchica', 'San Eduardo', 'San José de Pare', 'San Luis de Gaceno', 'San Mateo', 'San Miguel de Sema', 'San Pablo de Borbur', 'Santana', 'Santa María', 'Santa Rosa de Viterbo', 'Santa Sofía', 'Santamaría', 'Sativasur', 'Soatá', 'Socha', 'Sogamoso', 'Somondoco', 'Sora', 'Soracá', 'Suaita', 'Susacón', 'Sutamarchán', 'Sutatenza', 'Tasco', 'Tenza', 'Tibaná', 'Tibasosa', 'Toca', 'Togüí', 'Topagá', 'Tota', 'Tununguá', 'Turmequé', 'Tuta', 'Úmbita', 'Ventaquemada', 'Vergara', 'Villa de Leyva', 'Viracachá', 'Zetaquira'], shipping: { servientrega: 9000, interrapidisimo: 7500, days: '1-2 días' } },
  { id: 'CALDAS', name: 'Caldas', cities: ['Manizales', 'Villamaría', 'Pereira', 'Armenia', 'La Dorada', 'Chinchiná', 'Neira', 'Filadelfia', 'Pensilvania', 'Samaná', 'Marulanda', 'Risaralda', 'Belalcázar', 'Supía', 'Marmato', 'Aranzazu', 'Neira', 'Anserma', 'Belén de Umbría', 'Cartago', 'La Victoria', 'Obando', 'San José', 'Viterbo', 'Alcalá', 'Palestina', 'La Merced', 'Salento', 'Filandia', 'Pijao', 'Quimbaya', 'Circasia', 'Granada', 'Córdoba', 'Genova', 'Barragán'], shipping: { servientrega: 10000, interrapidisimo: 8500, days: '1-2 días' } },
  { id: 'CAQUETA', name: 'Caquetá', cities: ['Florencia', 'San Vicente del Caguán', 'Puerto Rico', 'Belén', 'Cartagena del Chairá', 'Curillo', 'El Doncello', 'El Paujil', 'La Montañita', 'Milán', 'Morelia', 'Puerto Luz', 'San José del Fragua', 'San Vicente del Caguán', 'Solano', 'Solita', 'Valparaíso', 'Albania', 'Consacá', 'El Tablón', 'La Cruz', 'Mocoa', 'Orito', 'Pasto', 'Popayán', 'Piamonte', 'Putumayo', 'San Francisco', 'Santiago', 'Sibundoy', 'Tablón de Tamara', 'Villagarzón'], shipping: { servientrega: 16000, interrapidisimo: 13000, days: '3-4 días' } },
  { id: 'CASANARE', name: 'Casanare', cities: ['Yopal', 'Aguazul', 'Villanueva', 'Tauramena', 'Maní', 'Monterrey', 'Pore', 'Trinidad', 'San Luis de Palenque', 'Nunchía', 'Sácama', 'Chámeza', 'Salinas', 'Caráchal', 'Recetor', 'San Andrés', 'La Esperanza', 'Macaguan', 'Támara', 'Orocué', 'Sinaloa', 'Hato Corozal', 'La Paz', 'Cabo Verde', 'San José de Ocoa', 'Tota'], shipping: { servientrega: 10000, interrapidisimo: 8500, days: '1-2 días' } },
  { id: 'CAUCA', name: 'Cauca', cities: ['Popayán', 'Santander de Quilichao', 'Patía', 'El Tambo', 'Piendamó', 'Cajibío', 'Bolívar', 'Buenos Aires', 'Caldono', 'Corinto', 'Inzá', 'La Sierra', 'La Vega', 'Morales', 'Páez', 'Pito', 'Rosas', 'San Sebastián', 'Santa Rosa', 'Sotará', 'Suárez', 'Timbío', 'Timbiquí', 'Toribío', 'Totoro', 'Almaguer', 'Argelia', 'Balboa', 'Bolívar', 'Cerbelo', 'El Diamante', 'El Patía', 'Flores', 'Guachené', 'Jambaló', 'López', 'Mercaderes', 'Miranda', 'Padilla', 'Páez', 'Puerto Tejada', 'Puracé', 'Rosario', 'San Lorenzo', 'San Pedro', 'Santa María', 'Silvia', 'Sotará', 'Sucre', 'Toribío', 'Totoró'], shipping: { servientrega: 14000, interrapidisimo: 11500, days: '2-3 días' } },
  { id: 'CESAR', name: 'Cesar', cities: ['Valledupar', 'Aguachica', 'Bosconia', 'Chimichagua', 'Chiriguaná', 'Curumaní', 'El Copey', 'El Paso', 'Gamarra', 'González', 'La Gloria', 'La Jagua de Ibirico', 'La Paz', 'Manaure Balcón del Cesar', 'Pailitas', 'Pelaya', 'Pueblo Bello', 'Río de Oro', 'San Alberto', 'San Diego', 'San Martín', 'Tamalameque', 'Becerril', 'Candelaria', 'Castalletes', 'Cerro de San Antonio', 'Ciénaga', 'Clemencia', 'El Piñón', 'El Retén', 'Fundación', 'Galeras', 'Nueva Granada', 'Pivijay', 'Plato', 'Remolino', 'Sabanas de San Ángel', 'Salamina', 'San Sebastián de Buenvista', 'Santa Ana', 'Santa Bárbara de Pinto', 'Santiago', 'Santo Tomás', 'Zona Bananera'], shipping: { servientrega: 18000, interrapidisimo: 15000, days: '3-4 días' } },
  { id: 'CHOCO', name: 'Chocó', cities: ['Quibdó', 'Istmina', 'Condoto', 'Bagadó', 'Bahía Solano', 'Bajo Baudó', 'Bojayá', 'Cantón de San Pablo', 'Carmen del Darién', 'Cértegui', 'Condoto', 'El Atrato', 'El Carmen de Atrato', 'El Carmen del Darién', 'Istmina', 'Juradó', 'Lloró', 'Medio Atrato', 'Medio Baudó', 'Nóvita', 'Nuquí', 'Quibdó', 'Río Iro', 'Río Quito', 'San José del Palmar', 'Sipí', 'Tadó', 'Unguía', 'Alto Baudó', 'Audiencia', 'Berruguilla', 'Bijao', 'Boca de Pepú', 'Bojayá', 'Caimalito', 'Citag', 'Dar', 'El Carmen', 'La Ye', 'Nauca', 'Nuquí', 'Pizarro', 'Playa de Oro', 'Puerto Echeverry', 'San Juan', 'Santa Rita', 'Sipí', 'Tadó', 'Telué', 'Tutunendo', 'UmIR', 'Villa Claret'], shipping: { servientrega: 22000, interrapidisimo: 18000, days: '4-5 días' } },
  { id: 'CUNDINAMARCA', name: 'Cundinamarca', cities: ['Bogotá', 'Zipaquirá', 'Facatativá', 'Girardot', 'Chía', 'Soacha', 'Funza', 'Madrid', 'Cajicá', 'Tocancipá', 'Sopó', 'La Calera', 'Guasca', 'Guatavita', 'Nemocón', 'Suesca', 'Cáchira', 'Carmen de Carupa', 'San Cayetano', 'Uttica', 'Vergara', 'Paratebueno', 'Manta', 'Pullopó', 'Ubala', 'Ubalá', 'Gachalá', 'Gachetá', 'Gama', 'Guasca', 'Guatas', 'Junín', 'La Pecha', 'Lenguazaque', 'Machetá', 'Manta', 'Medina', 'Nimaima', 'Nocaima', 'Pacho', 'Paime', 'Pandi', 'Puerto Salgar', 'Quebradanegra', 'Quipile', 'Ricaurte', 'San Antonio de Tequendama', 'San Francisco', 'San Juan de Rioseco', 'Sesquilé', 'Sibate', 'Silvania', 'Simijaca', 'Sopó', 'Subachoque', 'Suesca', 'Supatá', 'Susaguá', 'Tabio', 'Tausa', 'Tena', 'Tenjo', 'Tibacuy', 'Tibirto', 'Tocancipá', 'Tota', 'Villa de San Diego de Ubaté', 'Yacopí', 'Zipaquirá'], shipping: { servientrega: 8000, interrapidisimo: 6500, days: '1-2 días' } },
  { id: 'GUAINIA', name: 'Guainía', cities: ['Inírida', 'Barrancominas', 'Cuarauro', 'Mapiripana', 'Pana Pana', 'Puerto Colombia', 'Puerto España', 'Puerto Santander', 'San Felipe', 'San José', 'Valledupar'], shipping: { servientrega: 45000, interrapidisimo: 38000, days: '7-8 días' } },
  { id: 'GUAVIARE', name: 'Guaviare', cities: ['San José del Guaviare', 'Calamar', 'El Retorno', 'Miraflores', 'Nápoles', 'Puerto Concordia', 'Puerto Rico', 'San Fernando', 'Santa Rita', 'Santa Rosalía'], shipping: { servientrega: 22000, interrapidisimo: 18000, days: '4-5 días' } },
  { id: 'HUILA', name: 'Huila', cities: ['Neiva', 'Pitalito', 'Garzón', 'La Plata', 'Campoalegre', 'Teruel', 'Baraya', 'Yaguará', 'Iquira', 'Colombia', 'Santa María', 'Suaza', 'Palestina', 'Opet', 'Timar', 'San Ambrosio', 'El Agrado', 'Altamira', 'Becerrán', 'Aipe', 'Algeciras', 'Anolaima', 'Baraya', 'Campoalegre', 'Colombia', 'El Pital', 'El Agrado', 'Garzón', 'Gigante', 'Guadalupe', 'Hobo', 'Iquira', 'Isnos', 'La Argentina', 'La Plata', 'Nátaga', 'Neiva', 'Oporapa', 'Paicol', 'Palermo', 'Pital', 'Pitalito', 'Rivera', 'Saladoblanco', 'San Agustín', 'Santa María', 'Suaza', 'Tarqui', 'Tello', 'Teruel', 'Tesalia', 'Timaná', 'Villavieja', 'Yaguará'], shipping: { servientrega: 9000, interrapidisimo: 7500, days: '1-2 días' } },
  { id: 'LA_GUAJIRA', name: 'La Guajira', cities: ['Riohacha', 'Maicao', 'Uribia', 'Manaure', 'Albania', 'Barrancas', 'Dibulla', 'El Molino', 'Fonseca', 'Hatonuevo', 'La Jagua del Pilar', 'Maicao', 'Manaure', 'Riohacha', 'San Juan del Cesar', 'Uribia', 'Villanueva', 'Distracción', 'Español', 'Fonseca', 'La Jagua del Pilar'], shipping: { servientrega: 26000, interrapidisimo: 22000, days: '4-5 días' } },
  { id: 'MAGDALENA', name: 'Magdalena', cities: ['Santa Marta', 'Ciénaga', 'El Banco', 'Aracataca', 'Cerro de San Antonio', 'Chivolo', 'Concordia', 'El Piñón', 'El Retén', 'Fundación', 'Guamal', 'Nueva Granada', 'Pivijay', 'Plato', 'Remolino', 'Sabanas de San Ángel', 'Salamina', 'San Sebastián de Buenvista', 'San Antonio', 'Santa Ana', 'Santa Bárbara de Pinto', 'Santana', 'Sitionuevo', 'Tenerife', 'Zona Bananera', 'Algarrobo', 'Aracataca', 'Balcones', 'Bañaderto', 'Bocatoc', 'Cerro', 'Chibolo', 'Chimichagua', 'Chivolo', 'Cienaga', 'Clemencia', 'Concordia', 'El Banco', 'El Piñón', 'El Retén', 'Fundación', 'Guamal', 'La Jagua', 'La Loma', 'Luruaco', 'Manatí', 'Margarita', 'Nueva Granada', 'Pedernales', 'Pivijay', 'Plato', 'Pueblo Viejo', 'Remolino', 'Salamina', 'San Ángel', 'San Sebastián', 'San Juan', 'Santa Marta', 'Santana', 'Sitionuevo', 'Tenerife', 'Zona Bananera'], shipping: { servientrega: 20000, interrapidisimo: 17000, days: '3-4 días' } },
  { id: 'META', name: 'Meta', cities: ['Villavicencio', 'Granada', 'Puerto López', 'Acacías', 'San Martín', 'Puerto Gaitán', 'Mesetas', 'Leiva', 'Mapiripán', 'Campoalegre', 'Cubarral', 'San Juan de Arama', 'Vistahermosa', 'La Macarena', 'Puerto Concordia', 'Cabuyaro', 'El Castillo', 'El Dorado', 'Guamal', 'Puerto Lleras', 'Puerto Rico', 'Restrepo', 'San Carlos de Guaroa', 'San Juan de Arama', 'Uribe', 'Vista Hermosa'], shipping: { servientrega: 5000, interrapidisimo: 4000, days: '1 día' } },
  { id: 'NARIÑO', name: 'Nariño', cities: ['Pasto', 'Ipiales', 'Tumaco', 'Pastos', 'Barbacoas', 'Cumbitara', 'El Charco', 'El Rosario', 'Francisco Pizarro', 'Iles', 'Imués', 'Leiva', 'Liná', 'Magüí', 'Mallama', 'Mosquera', 'Olaya Herrera', 'Ospina', 'Providencia', 'Puelapí', 'Roberto Payán', 'Samaná', 'San Bernardo', 'San José de Albán', 'San Pablo', 'Sandoná', 'Santa Cruz', 'Sapuyés', 'Túquerres', 'Yacuanquer', 'Aldana', 'Ancuyá', 'Arboleda', 'Belén', 'Buesaco', 'Chachagui', 'Colón', 'Consacá', 'Contadero', 'Cuaspud', 'Cumbal', 'Cumbus', 'El Tablón', 'El Tambo', 'Funes', 'Guaitarilla', 'Gualmatán', 'Iles', 'Imués', 'Ipiales', 'La Cruz', 'La Florida', 'La Llanada', 'La Unión', 'Leiva', 'Linares', 'Los Andes', 'Maggí', 'Mallama', 'Mosquera', 'Nariño', 'Olaya Herrera', 'Ospina', 'Pasto', 'PEDERNALES', 'Pío', 'Providencia', 'Puelapí', 'Pupiales', 'Ricaurte', 'Río Bobo', 'Roberto Payán', 'Samaná', 'San Bernardo', 'San Lorenzo', 'San Pablo', 'San Pedro de Cartago', 'Sandoná', 'Santa Cruz', 'Santander', 'Sapuyés', 'Taminango', 'Tangua', 'Túquerres', 'Yacuanquer'], shipping: { servientrega: 24000, interrapidisimo: 20000, days: '4-5 días' } },
  { id: 'NORTE_SANTANDER', name: 'Norte de Santander', cities: ['Cúcuta', 'Ocaña', 'Pamplona', 'Villa del Rosario', 'Los Patios', 'El Zulia', 'Saravena', 'Tame', 'Abrego', 'Convención', 'Teorama', 'El Carmen', 'La Playa', 'Bochalema', 'Chinacota', 'Arboledas', 'Gramalote', 'Cáchira', 'Cucutilla', 'Durania', 'El Tarra', 'Gramalote', 'Hacarí', 'La Esperanza', 'La Playa', 'Labateca', 'Lourdes', 'Mutiscua', 'Pamplonita', 'Ragonvalia', 'Salazar', 'San Calixto', 'San Cayetano', 'Santiago', 'Santo Domingo', 'Sardinata', 'Silos', 'Teorama', 'Tibú', 'Tolochin', 'Vera', 'Villa Caro', 'Villa del Rosario', 'Ábrego', 'Arboleda', 'Bochalema', 'Bucarasica', 'Cácota', 'Cachirá', 'Cali', 'Chinácota', 'Chitagá', 'Convención', 'Cúcuta', 'Cucutilla', 'Durania', 'El Carmen', 'El Tarra', 'El Zulia', 'Gramalote', 'Hacarí', 'Herrán', 'La Esperanza', 'La Gloria', 'La Playa', 'Labateca', 'Los Patios', 'Lourdes', 'Mutiscua', 'Ocaña', 'Pamplonita', 'Pueblo Nuevo', 'Ragonvalia', 'Salazar', 'San Calixto', 'San Cayetano', 'Santiago', 'Santo Domingo', 'Sardinata', 'Silos', 'Teorama', 'Tibú', 'Tolochin', 'Villa Caro', 'Villa del Rosario'], shipping: { servientrega: 14000, interrapidisimo: 11500, days: '2-3 días' } },
  { id: 'PUTUMAYO', name: 'Putumayo', cities: ['Mocoa', 'Puerto Asís', 'Sibundoy', 'Colón', 'Mocoa', 'Orito', 'Pasto', 'Puerto Caicedo', 'Puerto Guzmán', 'Puerto Leguízamo', 'San Francisco', 'San Miguel', 'Santiago', 'Sibundoy', 'Valle del Guamuez', 'Villagarzón', 'Leticia', 'Puerto Amazonas', 'El Encanto', 'La Chorrera', 'La Pedrera', 'Puerto Arica', 'Puerto Alegría', 'Puerto América', 'Tarapacá'], shipping: { servientrega: 20000, interrapidisimo: 17000, days: '4-5 días' } },
  { id: 'QUINDIO', name: 'Quindío', cities: ['Armenia', 'Calarcá', 'Montenegro', 'Pijao', 'Filandia', 'Salento', 'Quimbaya', 'Circasia', 'Granada', 'Córdoba', 'Genova', 'Barragán', 'La Tebaida', 'Sevilla'], shipping: { servientrega: 10000, interrapidisimo: 8500, days: '1-2 días' } },
  { id: 'RISARALDA', name: 'Risaralda', cities: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'La Virginia', 'Marsella', 'Quinchía', 'Belén de Umbría', 'Apía', 'Santuario', 'Mistrató', 'Balboa', 'La Celia', 'Pueblo Rico', 'Quinchía', 'Santa Rosa de Cabal'], shipping: { servientrega: 10000, interrapidisimo: 8500, days: '1-2 días' } },
  { id: 'SANTANDER', name: 'Santander', cities: ['Bucaramanga', 'Floridablanca', 'Girón', 'Barrancabermeja', 'Piedecuesta', 'San Gil', 'Barichara', 'Zapatoca', 'Sucre', 'Villanueva', 'Lebrija', 'Rionegro', 'El Playón', 'Cimitarra', 'Puerto Wilches', 'Sabana de Torres', 'Los Santos', 'Mogotes', 'San Joaquín', 'Valle de San José', 'Cerro de San Antonio', 'Concepción', 'Enciso', 'Gámbita', 'Guaca', 'Güepsa', 'Hato', 'Jordán', 'La Belleza', 'La Paz', 'Muñoz', 'Ocamonte', 'Oiba', 'Onzaga', 'Palmar', 'Páramo', 'Pinchote', 'Puerto Parra', 'San Benito', 'San Miguel', 'Santa Helenia', 'Santa Rosa', 'Simacota', 'Suaita', 'Sucre', 'Suratá', 'Tona', 'Úraga', 'Vetas', 'Zapatoca', 'Albania', 'Barichara', 'Betulia', 'Cabrera', 'California', 'Capitanejo', 'Carrasquilla', 'Charta', 'Chimá', 'Concepción', 'Confines', 'Contratación', 'Corosoro', 'Curití', 'El Guacamayo', 'El Peñón', 'El Encino', 'Florián', 'Floridablanca', 'Gámbita', 'Girón', 'Guaca', 'Güepsa', 'Hato', 'Jesús María', 'La Belleza', 'La Paz', 'Landázuri', 'Lebrija', 'Los Santos', 'Macarito', 'Mogotes', 'Molagavita', 'Ocamonte', 'Oiba', 'Onzaga', 'Palmar', 'Páramo', 'Piedecuesta', 'Pinchote', 'Puente Nacional', 'Puerto Parra', 'Puerto Wilches', 'Rionegro', 'Sabana de Torres', 'San Andrés', 'San Benito', 'San Felipe', 'San Gil', 'San Joaquín', 'San Miguel', 'San Vicente de Chucurí', 'Santa Bárbara', 'Santa Helena', 'Santa Rosa', 'Simacota', 'Socorro', 'Suaita', 'Sucre', 'Suratá', 'Tona', 'Valle de San José', 'Vetas', 'Villanueva', 'Zapatoca'], shipping: { servientrega: 12000, interrapidisimo: 10000, days: '2-3 días' } },
  { id: 'SUCRE', name: 'Sucre', cities: ['Sincelejo', 'Corozal', 'Sampués', 'Coveñas', 'San Benito Abad', 'San Marcos', 'San Onofre', 'Santiago de Tolú', 'Buenavista', 'Chalán', 'Colosó', 'El Roble', 'Galeras', 'Guaranda', 'La Unión', 'Los Palmitos', 'Majagual', 'Morroa', 'Ovejas', 'Palmito', 'Sampués', 'San Benito Abad', 'San Juan de Betulia', 'San Marcos', 'San Onofre', 'Santiago de Tolú', 'Sincé', 'Sucre', 'Tolú Viejo'], shipping: { servientrega: 18000, interrapidisimo: 15000, days: '3-4 días' } },
  { id: 'TOLIMA', name: 'Tolima', cities: ['Ibagué', 'Espinal', 'Melgar', 'Honda', 'Lérida', 'Armero', 'Mariquita', 'Purificación', 'Natagaima', 'Ortega', 'Chaparral', 'Coyaima', 'Santa Isabel', 'Venadillo', 'Saldaña', 'Anzoátegui', 'Valle de San Juan', 'Santo Domingo', 'Córdoba', 'Rovira', 'Carmen de Apicalá', 'Icononzo', 'Flandes', 'Girardot', 'Hernandarias', 'Planadas', 'Rioblanco', 'Alvarado', 'Anzoátegui', 'Cajamarca', 'Casabianca', 'Chaparral', 'Coello', 'Coyaima', 'Cunday', 'Dolores', 'Espinal', 'Flandes', 'Fresno', 'Guamo', 'Honda', 'Ibagué', 'Icononzo', 'Lérida', 'Libano', 'Mariquita', 'Melgar', 'Murillo', 'Natagaima', 'Ortega', 'Palocabildo', 'Piedras', 'Planadas', 'Prado', 'Purificación', 'Rioblanco', 'Rovira', 'Saldaña', 'San Antonio', 'Santa Isabel', 'Santo Domingo', 'Suárez', 'Tolú', 'Valle de San Juan', 'Venadillo', 'Villahermosa', 'Icononzo'], shipping: { servientrega: 9000, interrapidisimo: 7500, days: '1-2 días' } },
  { id: 'VALLE_CAUCA', name: 'Valle del Cauca', cities: ['Cali', 'Palmira', 'Buenaventura', 'Tuluá', 'Buga', 'Cartago', 'Yumbo', 'Candelaria', 'Guadalajara de Buga', 'Jamundí', 'Pastales', 'Pradera', 'Restrepo', 'San Pedro', 'Yotoco', 'Alcalá', 'Andalucía', 'Ansermanuevo', 'Argelia', 'Bolívar', 'Buenaventura', 'Buga', 'Bugalagrande', 'Caicedonia', 'Cali', 'Calima', 'Candelaria', 'Cartago', 'Dagua', 'El Águila', 'El Cairo', 'El Cerrito', 'El Dovio', 'Florida', 'Ginebra', 'Guacarí', 'Guadalajara', 'Jamundí', 'La Cairo', 'La Puma', 'La Unión', 'La Victoria', 'Obando', 'Palmira', 'Pradera', 'Restrepo', 'Riofrío', 'Roldanillo', 'San Pedro', 'Santiago de Cali', 'Sevilla', 'Toro', 'Tulúa', 'Trujillo', 'Ulloa', 'Versalles', 'Vijes', 'Yotoco', 'Yumbo', 'Zarzal'], shipping: { servientrega: 14000, interrapidisimo: 11500, days: '2-3 días' } },
  { id: 'VAUPES', name: 'Vaupés', cities: ['Mitú', 'Carurú', 'Papunaua', 'Taraira', 'Yavaraté', 'Colón', 'Mitu', 'Papun', 'Taraira', 'Vaupés'], shipping: { servientrega: 45000, interrapidisimo: 38000, days: '7-8 días' } },
  { id: 'VICHADA', name: 'Vichada', cities: ['Puerto Carreño', 'Cumaribo', 'La Primavera', 'Puerto Carreño', 'Santa Rosalía'], shipping: { servientrega: 30000, interrapidisimo: 25000, days: '5-6 días' } },
  { id: 'GUAJIRA', name: 'La Guajira', cities: ['Riohacha', 'Maicao', 'Uribia', 'Manaure', 'Albania', 'Barrancas', 'Dibulla', 'El Molino', 'Fonseca', 'Hatonuevo', 'La Jagua del Pilar', 'San Juan del Cesar', 'Villanueva'], shipping: { servientrega: 26000, interrapidisimo: 22000, days: '4-5 días' } },
];

export function getCheapestShipping(departmentId: string): { price: number; carrier: string; days: string } | null {
  const dept = COLOMBIA_DEPARTMENTS.find(d => d.id === departmentId);
  if (!dept) return null;
  
  if (dept.shipping.interrapidisimo < dept.shipping.servientrega) {
    return { price: dept.shipping.interrapidisimo, carrier: 'Interrapidisimo', days: dept.shipping.days };
  }
  return { price: dept.shipping.servientrega, carrier: 'Servientrega', days: dept.shipping.days };
}

export function validateAddress(address: string): boolean {
  const patterns = [
    /^Cra\s*\d+/i,
    /^Calle\s*\d+/i,
    /^Av\.?\s*\d+/i,
    /^Transversal\s*\d+/i,
    /^Diagonal\s*\d+/i,
    /^Cra\s*\d+\s*#\d+-\d+/i,
    /^Calle\s*\d+\s*#\d+-\d+/i,
  ];
  return patterns.some(p => p.test(address.trim()));
}

export function formatCOP(amount: number): string {
  return new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(amount) + ' COP';
}